### ISSUE TITLE
用法的注释建议改为中文

### ISSUE THREAD

**Issue by XYZscratcher** [beavailable/share#1]
这个工具我觉得非常好用，就是用法有点看不懂。

**Comment by beavailable** [comment]
README.md 里面关于用法的介绍来自`-h`选项，而`-h`选项的输出使用英文是为了避免在部分场景下出现乱码的问题。

你有哪里看不懂，可以指出来，我尽量解释一下。

**Comment by XYZscratcher** [comment]
谢谢你及时地回应！以下是我的问题。

1. ```-b```选项的”地址“是指什么？

1. -b、-p选项的语法是如```-p 2022``` ```-b xxx```这样的吗？

1.  命令的语法是直接键入选项还是前面要加```share.py```？

**Comment by beavailable** [comment]
1. 地址就是指 IP 地址，比如`127.0.0.1`
2. 是的
3. 对于 windows，运行 python 脚本的语法应该是形如`python share.py -b xxx -p yyy`这样的；对于 linux，可以用`share.py -b xxx -p yyy`

**Comment by XYZscratcher** [comment]
原来是在cmd上运行啊！搞了半天我是在IDLE上运行
