### ISSUE TITLE
把目录设置为磁盘根目录，且未开启-a参数时，打不开首页

### ISSUE THREAD

**Issue by WHJWNAVY** [beavailable/share#3]
## 把目录设置为磁盘根目录，且未开启-a参数时，打不开首页
* ![图片](https://user-images.githubusercontent.com/16632096/229396379-f073e803-13e4-41cd-a51d-f0890a471102.png)
* ![图片](https://user-images.githubusercontent.com/16632096/229396451-82dced66-e8ed-42ae-aa53-e45b2298b52f.png)
* ![图片](https://user-images.githubusercontent.com/16632096/229396481-1da400ae-b627-4d6c-91e5-ff4169fe9825.png)

## 因为此盘根目录下默认有两个隐藏文件夹:
* ***$RECYCLE.BIN***
* ***`System Volume Information`***
![图片](https://user-images.githubusercontent.com/16632096/229396682-36532c87-5d4f-40ca-9d3c-efdfd2f4a171.png)

**Comment by beavailable** [comment]
感谢反馈，我刚刚检查了下，你说的问题确实存在。

但不是因为根目录下有隐藏文件/目录，而是因为根目录**自身**带有 hidden 属性导致被判断成隐藏目录，不知道 windows 为什么设计成这样。

无论如何这是一个 bug，而且受影响的不只是根目录，如果你尝试分享任意一个隐藏目录而不开启`-a`选项都会触发这个 bug。

已修复。
