### ISSUE TITLE
py文件中文乱码

### ISSUE THREAD

**Issue by YBxbxxz** [beavailable/share#4]
预览py文件时，中文乱码

**Comment by beavailable** [comment]
乱码是一个无法避免的问题，因为不同的文本文件可能有不同的编码方式，而程序没有办法知道某个具体的文件的编码方式是什么，也无法将此信息告知浏览器，浏览器使用其默认的编码方式来解码就可能得到乱码。

虽然有一些库可以检测文件编码，但我不想引入外部依赖，所以这个问题没有特别好的解决办法。

我刚刚发现，Windows 10 2021 ltsc 中的记事本已经默认使用`utf-8`了，所以我认为将文本文件的`Content-Type`中的`charset`指定为`utf-8`可能是一个好的选择，这样应该可以解决大部分情况下的乱码问题。

稍后我会提交一个 commit 来解决此问题，但是请注意，对于非`utf-8`的文本文件，浏览器中依然可能显示乱码，且此问题无法解决。

**Comment by YBxbxxz** [comment]
👍
